env:
  token: ${{ secrets.ACCESS_TOKEN }}
  
name: Update incident

on:
  issues:
    types:
      - closed

jobs:
  run_scripts:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Run read_comment.sh
        run: |
          chmod +x ./read_comment.sh
          ./read_comment.sh
        shell: bash
      - name: Run update package.json
        run: |
          chmod +x ./update_packages.sh
          ./update_packages.sh
        shell: bash

      - name: Run dependency_updates.sh
        run: |
          chmod +x ./dependency_updates.sh
          ./dependency_updates.sh
        shell: bash
