env:
 token: ${{ secrets.TOKEN }}

name: Trigger Workflow in 2 days

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 */1 * *"

jobs:
  run_tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run script file
      run: |
        chmod +x ./open_issues_Alert1.sh
        ./open_issues_Alert1.sh
        chmod +x ./reminder_comment.sh
        ./reminder_comment.sh
      shell: bash
